### ISSUE TITLE
After gulp.dest('dist') the vinyl path changes to dist

### ISSUE THREAD

**Issue by stevemao** [gulpjs/vinyl-fs#76] opened 2015-07-10 02:19 UTC
per https://github.com/gulpjs/gulp/pull/1067

vinyl path shouldn't be changed after gulp.dest

**Comment by contra** [comment] 2015-07-10 20:32
This behavior was intended, .dest streams should modify the file path to be the new path so that files down the stream refer to the path the file was most recently on the file system at.

**Comment by stevemao** [comment] 2015-07-10 22:47
Then you need to go ahead and merge gulpjs/gulp#1067. ping @sindresorhus @contra 
Either one of you guys is wrong.

**Comment by sindresorhus** [comment] 2015-07-10 22:51
I see it being documented: https://github.com/wearefractal/vinyl-fs#destfolder-opt But it was a total surprise for me, and I have real doubts how expected that behaviour is. I assumed `dest` would just write the files and I could continue using them as nothing had happened.

**Comment by stevemao** [comment] 2015-07-10 23:31
hm....
> I assumed dest would just write the files and I could continue using them as nothing had happened.

This was my instinct too. But it kinda make sense after I read the doc.

```
The file will be modified after being written to this stream:
cwd, base, and path will be overwritten to match the folder
stat.mode will be overwritten if you used a mode parameter
contents will have it's position reset to the beginning if it is a stream
```

**Comment by sindresorhus** [comment] 2015-07-10 23:40
Just realized the `passthrough` option is kinda misleading now. Since the PassThrough stream in Node doesn't touch the input:

> This is a trivial implementation of a Transform stream that simply passes the input bytes across to the output.

It's not really passed through then, it's transformed.

**Comment by stevemao** [comment] 2015-07-11 03:25
Hm... it shouldn't be called `passthrough`. Maybe something like `duplexMode`?

**Comment by contra** [comment] 2015-07-14 06:33
@sindresorhus dest has no passthrough option, confused as to what you mean

**Comment by phated** [comment] 2015-12-16 22:03
I think this is the desired behavior, I'm going to close this and open a docs issue and mention that this should be near the top of the docs for the `dest` method.

**Closed** 2015-12-16 22:13 UTC
