### ISSUE TITLE
Negation of patterns including parent directories (../) seems not to work.

### ISSUE THREAD

**Issue by calvinjuarez** [gulpjs/vinyl-fs#306] opened 2018-11-30 20:00 UTC
**Given:**
_File structure:_
```
/
├┬ src/
|├ File.js
|├ File.spec.js
│└ FileSpec.js
└┬ build/
 └ gulpfile.js
```
_Glob array:_
```js
[
  '../src/**/*.js',
  '!../**/*{s,S}pec.js',
]
```

**What were you expecting to happen?**
The `!` negation pattern would exclude the spec files from the stream.  Given the gulpfile below, I expect to see something like this when I run `gulp`:

```
...
[00:00:00] gulp-debug: ../src/deep/File.js
[00:00:00] gulp-debug: 1 item
...
```

**What actually happened?**

The negation pattern doesn't seem to apply correctly.  Given the gulpfile below, I actually see something like this when I run `gulp`:

```
...
[00:00:00] gulp-debug: ../src/deep/File.js
[00:00:00] gulp-debug: ../src/deep/File.spec.js
[00:00:00] gulp-debug: ../src/deep/FileSpec.js
[00:00:00] gulp-debug: 3 items
...
```

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**

_gulpfile.js_
```js
const gulp = require('gulp')
const debug = require('gulp-debug')

const FILES = [
  '../src/**/*.js',
  '!../**/*{s,S}pec.js',

  // or even any of these
  '!../**/*spec.js',
  '!../**/*Spec.js',
  '!../src/**/*{s,S}pec.js',
  '!../src/*{s,S}pec.js',
  // or even the file path specifically
  '!../src/File.spec.js',
  '!../src/FileSpec.js',
]

gulp.task('default', function () {
  return gulp.src(FILES).pipe(debug())
})
```

**What version of gulp are you using?**

Gulp 4.  (Notably, Gulp 3 works as expected.)

**What versions of npm and node are you using?**

- node v11.1.0
- npm 6.4.1

**This is a .zip file of the reduced test case as described above.**  FWIW, the zip also includes a _build-with-gulp-v3/_ directory that allows comparing to gulp v3.9.1 behavior.

[gulp-negation-issue.zip](https://github.com/gulpjs/vinyl-fs/files/2634792/gulp-negation-issue.zip)

**Comment by calvinjuarez** [comment] 2018-11-30 20:04
**Update:**  Apologies, in the ZIP above, _build/gulpfile.js_ lines 14-15 should look like this:
```js
	'!../src/File.spec.js',
	'!../src/FileSpec.js',
```

(The `deep/` was from a time I thought more complex globbing was necessary to replicate the issue.)

**Comment by phated** [comment] 2018-11-30 20:13
This has already been reported at https://github.com/gulpjs/gulp/issues/2211

There's a workaround in that thread, as we likely won't have a chance to look into this any time soon.

**Comment by calvinjuarez** [comment] 2018-11-30 20:22
@phated Thanks!  I searched both here and there, but clearly not well enough.  :P

**Comment by phated** [comment] 2018-11-30 20:40
Using the cwd option would be a major refactor?

It's likely an issue in node-glob because we rely on it for negation now (we used to do it ourselves but it was massively slower)

**Comment by calvinjuarez** [comment] 2018-11-30 21:23
Whoops!  Missed that one for the comment before it!  😳  So sorry.  `cwd` will probably do me just fine, I think.  Thanks again!

**Comment by phated** [comment] 2023-06-11 21:40
We switched our implementation of to-absolute-glob to a fork that supports this. I'll add a regression test and close this out.

**Closed** 2023-06-11 21:48 UTC
