### ISSUE TITLE
The addition of futimes appears to break unbuffered streams

### ISSUE THREAD

**Issue by Klowner** [gulpjs/vinyl-fs#137] opened 2015-12-18 18:07 UTC
I'm pretty sure this test shouldn't fail, right?
https://github.com/Klowner/vinyl-fs/tree/bug-futimes-hates-buffered-false

Appears to be an issue in `dest/writeContents/writeStream.js`. I assume that `outStream` is actually closed by the time `futimes(outFD, stat, complete)` is called. This may be a graceful-fs bug? I'll look into it further if someone cares to confirm.

**Comment by phated** [comment] 2015-12-18 18:52
@Klowner this is what I was running into yesterday, couldn't track down the root cause but it is probably closed at that point.

**Comment by Klowner** [comment] 2015-12-18 20:58
Thanks for confirming @phated.

Looks like it's not an issue with graceful-fs, as normal fs appears to exhibit the same behavior. That is, a WriteStream's associated file descriptor is closed by the time the `'finish'` event is fired. I suppose the easy solution would be to just re-open the output file and call futimes on it, but it would be nice to avoid that.

**Comment by phated** [comment] 2015-12-18 21:46
Should be closed by the fix in #138

**Closed by phated** 2015-12-18 21:46 UTC
